version: "3.7"

##
# Project-specific CI environment extensions
##

services:

  # cicee execution service.
  ci-exec:
    # depends_on:
    #   - pg
    environment:
      # Environment variables with only a key are resolved to their values on the machine running (Docker) Compose.
      #--
      # Project
      #--
      NUGET_API_KEY:
      NUGET_SOURCE:
    # NOTE: Root user specified below helps address permissions errors when using the default CICEE Dockerfile.
    user: root
    volumes:
      # Volumes below prevent collisions between working directory dependencies across architectures/OSes (local vs docker-compose).
      - /code/src/bin/
      - /code/src/obj/
      - /code/tests/unit/bin/
      - /code/tests/unit/obj/
