name: Publish Release

on:
  push:
    branches:
      - main
      - master

jobs:
  publish-release:
    # ubuntu-latest provides many dependencies.
    # See: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v2
      - name: Restore local .NET tools (including cicee)
        run: dotnet tool restore
      - name: Execute publish script - Publish project artifacts
        run: dotnet cicee exec -c ci/bin/publish.sh
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: ${{secrets.NUGET_SOURCE}}
          RELEASE_ENVIRONMENT: true
